Repository Automattic/Gravatar-SDK-Android, pull requests merged in 2025-06, with the labels that each got.

#649 Update usage-quickeditor.md
  docs/get-started/usage-quickeditor.md
  docs/images/about_editor_all_fields.png
  docs/images/about_editor_two_fields.png
  docs/images/avatar_and_about.gif
  docs/images/avatar_picker_horizontal.png
  docs/images/avatar_picker_vertical.png
Labels: documentation

#650 Don't apply -SNAPSHOT to dokka version
  build.gradle.kts
Labels: documentation

#652 Update the AboutMe input field's height
  gravatar-quickeditor/screenshotTests/roborazzi/com.gravatar.quickeditor.ui.abouteditor.AboutEditorTest.aboutEditorLoaded.png
  gravatar-quickeditor/screenshotTests/roborazzi/com.gravatar.quickeditor.ui.abouteditor.AboutEditorTest.aboutEditorLoadedDark.png
  gravatar-quickeditor/screenshotTests/roborazzi/com.gravatar.quickeditor.ui.abouteditor.AboutEditorTest.aboutEditorLoadedLandscape.png
  gravatar-quickeditor/screenshotTests/roborazzi/com.gravatar.quickeditor.ui.abouteditor.AboutEditorTest.aboutEditorPersonalLoaded.png
  gravatar-quickeditor/screenshotTests/roborazzi/com.gravatar.quickeditor.ui.abouteditor.AboutEditorTest.aboutEditorSaving.png
  gravatar-quickeditor/screenshotTests/roborazzi/com.gravatar.quickeditor.ui.abouteditor.AboutEditorTest.heightRestrictedAboutEditorLoaded.png
  gravatar-quickeditor/screenshotTests/roborazzi/com.gravatar.quickeditor.ui.editor.QuickEditorTest.quickEditorWithAboutEditor.png
  gravatar-quickeditor/screenshotTests/roborazzi/com.gravatar.quickeditor.ui.editor.QuickEditorTest.quickEditorWithAboutEditorLandscape.png
  gravatar-quickeditor/src/main/java/com/gravatar/quickeditor/ui/abouteditor/AboutEditorViewModel.kt
  gravatar-quickeditor/src/main/java/com/gravatar/quickeditor/ui/abouteditor/components/AboutEditField.kt
  gravatar-quickeditor/src/test/java/com/gravatar/quickeditor/ui/abouteditor/AboutEditorViewModelTest.kt
Labels: Bug, Android

#651 Bump AGP (8.10.1) and Gradle (8.14.1)
  .buildkite/shared-pipeline-vars
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: infra

#656 Add DSL like API for the QuickEditorScopeOption
  demo-app/src/main/java/com/gravatar/demoapp/ui/AvatarUpdateTab.kt
  gravatar-quickeditor/api/gravatar-quickeditor.api
  gravatar-quickeditor/src/main/java/com/gravatar/quickeditor/ui/editor/QuickEditorScopeConfiguration.kt
  gravatar-quickeditor/src/main/java/com/gravatar/quickeditor/ui/editor/QuickEditorScopeOption.kt
  gravatar-quickeditor/src/test/java/com/gravatar/quickeditor/ui/editor/QuickEditorScopeOptionTest.kt
Labels: Enhance

#659 Change tonal elevation to deafult (0.dp) of the bottom sheet
  gravatar-quickeditor/src/main/java/com/gravatar/quickeditor/ui/editor/bottomsheet/GravatarQuickEditorBottomSheet.kt
Labels: [Feature] Gravatar-Quickeditor

#663 Update the code in the usage-quickeditor.md
  docs/get-started/usage-quickeditor.md
Labels: documentation

#664 QE Top section updates
  gravatar-quickeditor/api/gravatar-quickeditor.api
  gravatar-quickeditor/screenshotTests/roborazzi/com.gravatar.quickeditor.ui.editor.QuickEditorTest.quickEditorWithoutEmail.png
  gravatar-quickeditor/src/main/java/com/gravatar/quickeditor/ui/components/ProfileCard.kt
  gravatar-quickeditor/src/main/java/com/gravatar/quickeditor/ui/editor/GravatarQuickEditorPage.kt
  gravatar-quickeditor/src/main/java/com/gravatar/quickeditor/ui/editor/QuickEditor.kt
  gravatar-quickeditor/src/main/java/com/gravatar/quickeditor/ui/editor/QuickEditorUiState.kt
  gravatar-quickeditor/src/main/java/com/gravatar/quickeditor/ui/editor/QuickEditorViewModel.kt
  gravatar-quickeditor/src/main/res/drawable/ic_external.xml
  gravatar-quickeditor/src/test/java/com/gravatar/quickeditor/ui/editor/QuickEditorTest.kt
  gravatar-quickeditor/src/test/java/com/gravatar/quickeditor/ui/editor/QuickEditorViewModelTest.kt
Labels: [Feature] Gravatar-Quickeditor

#666 Fix typo in "docs/sdk-technical-details/sdk-techincal-details.md"
  README.md
  docs/sdk-technical-details/sdk-technical-details.md
Labels: tech debt
