Repository Automattic/Gravatar-SDK-Android, pull requests merged in 2025-02, with the labels that each got.

#568 Fix: Avatar is not visible when the profile is disabled but the Avatar is set to public
  gravatar-quickeditor/screenshotTests/roborazzi/com.gravatar.quickeditor.ui.avatarpicker.AvatarPickerTest.avatarPickerListLoaded.png
  gravatar-quickeditor/screenshotTests/roborazzi/com.gravatar.quickeditor.ui.avatarpicker.AvatarPickerTest.avatarPickerListLoadedDark.png
  gravatar-quickeditor/screenshotTests/roborazzi/com.gravatar.quickeditor.ui.components.ProfileCardTest.profileCardDarkMode.png
  gravatar-quickeditor/screenshotTests/roborazzi/com.gravatar.quickeditor.ui.components.ProfileCardTest.profileCardLightMode.png
  gravatar-quickeditor/screenshotTests/roborazzi/com.gravatar.quickeditor.ui.oauth.OAuthPageTest.oAuthPageAuthorizing.png
  gravatar-quickeditor/screenshotTests/roborazzi/com.gravatar.quickeditor.ui.oauth.OAuthPageTest.oAuthPageDark.png
  gravatar-quickeditor/screenshotTests/roborazzi/com.gravatar.quickeditor.ui.oauth.OAuthPageTest.oAuthPageLight.png
  gravatar-quickeditor/src/main/java/com/gravatar/quickeditor/ui/avatarpicker/AvatarPicker.kt
  gravatar-quickeditor/src/main/java/com/gravatar/quickeditor/ui/components/ProfileCard.kt
  gravatar-quickeditor/src/main/java/com/gravatar/quickeditor/ui/oauth/OAuthPage.kt
  gravatar-quickeditor/src/main/java/com/gravatar/quickeditor/ui/oauth/OAuthUiState.kt
  gravatar-quickeditor/src/main/java/com/gravatar/quickeditor/ui/oauth/OAuthViewModel.kt
  gravatar-quickeditor/src/test/java/com/gravatar/quickeditor/ui/components/ProfileCardTest.kt
  gravatar-quickeditor/src/test/java/com/gravatar/quickeditor/ui/oauth/OAuthViewModelTest.kt
  gravatar-ui/api/gravatar-ui.api
  gravatar-ui/src/main/java/com/gravatar/ui/components/atomic/Avatar.kt
  gravatar-ui/src/main/res/values/strings.xml
Labels: Enhance, [Feature] Gravatar-UI, [Feature] Gravatar-Quickeditor

#570 Update translations
  gravatar-quickeditor/src/main/res/values-ar/strings.xml
  gravatar-quickeditor/src/main/res/values-de/strings.xml
  gravatar-quickeditor/src/main/res/values-es/strings.xml
  gravatar-quickeditor/src/main/res/values-fr/strings.xml
  gravatar-quickeditor/src/main/res/values-in/strings.xml
  gravatar-quickeditor/src/main/res/values-it/strings.xml
  gravatar-quickeditor/src/main/res/values-iw/strings.xml
  gravatar-quickeditor/src/main/res/values-ja/strings.xml
  gravatar-quickeditor/src/main/res/values-ko/strings.xml
  gravatar-quickeditor/src/main/res/values-nl/strings.xml
  gravatar-quickeditor/src/main/res/values-pt-rBR/strings.xml
  gravatar-quickeditor/src/main/res/values-ru/strings.xml
  gravatar-quickeditor/src/main/res/values-sv/strings.xml
  gravatar-quickeditor/src/main/res/values-tr/strings.xml
  gravatar-quickeditor/src/main/res/values-zh-rCN/strings.xml
  gravatar-quickeditor/src/main/res/values-zh-rTW/strings.xml
  gravatar-ui/src/main/res/values-ar/strings.xml
  gravatar-ui/src/main/res/values-de/strings.xml
  gravatar-ui/src/main/res/values-es/strings.xml
  gravatar-ui/src/main/res/values-fr/strings.xml
  gravatar-ui/src/main/res/values-in/strings.xml
  gravatar-ui/src/main/res/values-it/strings.xml
  gravatar-ui/src/main/res/values-iw/strings.xml
  gravatar-ui/src/main/res/values-ja/strings.xml
  gravatar-ui/src/main/res/values-ko/strings.xml
  gravatar-ui/src/main/res/values-nl/strings.xml
  gravatar-ui/src/main/res/values-pt-rBR/strings.xml
  gravatar-ui/src/main/res/values-ru/strings.xml
  gravatar-ui/src/main/res/values-sv/strings.xml
  gravatar-ui/src/main/res/values-tr/strings.xml
  gravatar-ui/src/main/res/values-zh-rCN/strings.xml
  gravatar-ui/src/main/res/values-zh-rTW/strings.xml
Labels: Translations

#577 Bump target&compile SDK to 35 in the demo app
  demo-app/build.gradle.kts
  demo-app/src/main/AndroidManifest.xml
  demo-app/src/main/java/com/gravatar/demoapp/theme/Theme.kt
  demo-app/src/main/java/com/gravatar/demoapp/ui/DemoGravatarApp.kt
Labels: :demoapp

#578 Bump uCrop to 2.2.11
  gradle/libs.versions.toml
Labels: dependencies

#579 Update translations
  gravatar-ui/src/main/res/values-ar/strings.xml
  gravatar-ui/src/main/res/values-de/strings.xml
  gravatar-ui/src/main/res/values-es/strings.xml
  gravatar-ui/src/main/res/values-fr/strings.xml
  gravatar-ui/src/main/res/values-in/strings.xml
  gravatar-ui/src/main/res/values-it/strings.xml
  gravatar-ui/src/main/res/values-iw/strings.xml
  gravatar-ui/src/main/res/values-ja/strings.xml
  gravatar-ui/src/main/res/values-ko/strings.xml
  gravatar-ui/src/main/res/values-nl/strings.xml
  gravatar-ui/src/main/res/values-pt-rBR/strings.xml
  gravatar-ui/src/main/res/values-ru/strings.xml
  gravatar-ui/src/main/res/values-sv/strings.xml
  gravatar-ui/src/main/res/values-tr/strings.xml
  gravatar-ui/src/main/res/values-zh-rCN/strings.xml
  gravatar-ui/src/main/res/values-zh-rTW/strings.xml
Labels: [Feature] Gravatar-UI, Translations

#584 Refactor Pipeline to use Github Notify
  .buildkite/pipeline.yml
Labels: infra

#589 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement.md
Labels: documentation
